### ISSUE TITLE
Runtime check for tox envs that won't run

### ISSUE THREAD

**Issue by ryanhiebert** [ryanhiebert/tox-travis#18]
From @jayvdb on #16:

> It could be possible to check that the .travis.yml matrix has all of the versions that are in tox.ini [tox:travis], as a quick run-time check and warning that the two files have been set up correctly / they haven't been shoved out of sync accidentally.

**Comment by ryanhiebert** [comment]
This isn't a bad idea, but I am concerned about the maintainability of it. Essentially, we'd have to be parsing the `.travis.yml`, and figuring out what we think Travis will do with it. I don't currently make any guesses like that, and instead let Travis tell me what it has done, and base the envlist on that.

I'm not opposed to the idea, but I'll want to see that it can be added in a maintainable way, and I'm not likely to invest time in it myself in the near future.

**Comment by jayvdb** [comment]
I am primarily interested in the very basic scenario where .travis.yml doesnt include a matrix or other complex configs. I.e. add a warning for the very simple problems only, to help beginners. This would be almost the same as generating a .travis.yml , except reverse: is the existing .travis.yml 'worse' than an automatically generated one?

A separate package for a `.travis.yml` parser would be needed for complex scenarios. I am sure that it would provide more useful functionality.

**Comment by ryanhiebert** [comment]
I think this feature probably isn't worth it. If somebody writes up an implementation that's reasonably simple and doesn't have false positives, I'd be willing to accept it, but I'm not personally inclined to push for it or write it myself. As such, I'm going to close this issue.

**Comment by jayvdb** [comment]
Note that the ruby travis yaml parser has been extracted out as https://github.com/travis-ci/travis-yaml , so creating a compatible python parser is more feasible now.
