### ISSUE TITLE
Simple osx support

### ISSUE THREAD

**Issue by jayvdb** [ryanhiebert/tox-travis#25]
While longer term ideas perculate, I think there is a simple approach possible for osx that doesnt prevent any future improvement, but is a little backwards incompatible for some edge cases.

Installing & using tox-travis on osx will currently run only the py27 testenv. Anything more complex requires a lot of ugly hacks. (Need to recheck this.)

tox-travis relies on TRAVIS_PYTHON_VERSION a lot, which is only provided with `language: python` on linux. Iirc, recently tox-travis added another similar envvar usable as an override.

Tox-travis could require this envvar is set, only on osx, or otherwise do not alter tox TOXENV. Python osx is not supported by Travis, but if it was supported it is very likely this envvar will be set.  By requiring it now, we default to normal tox behaviour on osx, but provide a clear approach for people who want to hack a fake travis support.

For the typical use of one osx job , normal tox processing will change from running the main testenv for only the default python , to running the testenv on whatever python versions are defined in `envlist`, which shouldnt break anything, however we would need to enable "skip missing interpretors" to avoid silly failures.

If someone has set the envvar manually for a osx job, it would work as before.

The backwards incompatibilities exist where someone has
- a `tox:travis` that they expect to be used on osx jobs. If they also have a normal `envlist` , it would be used and should work witbout error on osx, unless the have an osx bug.
- selected the desired python interpreter using `PATH`. They will also see all found interpreters being tested, and will be annoyed if they have multiple osx jobs retesting the same multiple interpreters. The may not notice this for a while, aa the most obvious clue will be an increase in build times.

I think these edge cases will exist in some form for any solution that provides osx support, as users are hacking around the lack of osx support by travis, in many curious ways.
I doubt there are many tox-travis users with osx jobs, but more users will arrive soon and we need a clear and simple approach for them.

**Comment by ryanhiebert** [comment]
> tox-travis relies on TRAVIS_PYTHON_VERSION a lot, which is only provided with language: python on linux. Iirc, recently tox-travis added another similar envvar usable as an override.

The environment variables that we use are `TRAVIS` (to make sure we're running on Travis before we do anything else), and `TRAVIS_PYTHON_VERSION` (to find which Python we need to use). We also check on `TOXENV` to make sure that if it's set we don't override it at all, and break it's functionality. (There's also one other variable that's used only for testing, but that's _very_ not public).

Until we've got an ideal solution, I'd recommend falling back to using `TOXENV` when using mac builds. This has no backward incompatibilities, and just uses the native features of tox. Unless we're providing something significantly better than that, I don't think it's worth adding anything else.
