### ISSUE TITLE
`install_command` Has No Effect on Travis

### ISSUE THREAD

**Issue by jhshi** [ryanhiebert/tox-travis#30]
My project needs to support `pypy` and depends on `numpy`.  I use the `install_command`  for the pypy env to install `numpy` for pypy from BitBucket before installing other pakcages. Here is my `tox.ini`:

```
[tox]
envlist = py27,pypy

[testenv]
commands = pytest
deps =
    pytest-pep8
    pytest-cov
    pytest
    coverage

[testenv:pypy]
install_command = pip install git+https://bitbucket.org/pypy/numpy.git {packages}
```
This works well locally. However, `numpy` seems not installed properly on Travis-CI: the `tox` command complains that `numpy` was not installed. Here is my `.travis.yml`:

```
language: python
python:
    - "2.7"
    - "pypy"
install:
    - |
        if [[ "${TRAVIS_PYTHON_VERSION}" = pypy ]]; then
            git clone https://github.com/yyuu/pyenv.git ~/.pyenv
            PYENV_ROOT="$HOME/.pyenv"
            PATH="$PYENV_ROOT/bin:$PATH"
            eval "$(pyenv init -)"
            pyenv install pypy-5.4.1
            pyenv global pypy-5.4.1
        fi
    - pip install tox-travis coveralls
script:
    - tox

after_success:
    - coveralls
```
I have to explicit call `pip install git+https://bitbucket.org/pypy/numpy.git` in the `if` block to make Travis happy. Is this potentially a glitch of `tox-travis`?

**Comment by ryanhiebert** [comment]
I won't rule it out, but I don't immediately see how that would happen. The way `tox-travis` works is that it parses configuration and environment to determine which envs to run, then passes things along to the `tox` command to take it the rest of the way.

**Comment by jayvdb** [comment]
Does it work if you manually create two travis jobs and set `TOXENV` to `py27` and `pypy`.
I.e. not using `tox-travis`.

**Comment by jhshi** [comment]
Uh, it failed with the TOXENV as well. This seems not a problem of `tox-travis`. Here is the build:

https://travis-ci.org/jhshi/wltrace/jobs/165248823#L185

Just out of curiosity, it seems `tox` didn't even try to install the deps at all (`inst` right after `sdist-make`). On my local machine, the logs were:

```
GLOB sdist-make: /home/jinghaos/projects/wltrace/setup.py
pypy create: /home/jinghaos/projects/wltrace/.tox/pypy
pypy installdeps: pytest-pep8, pytest-cov, pytest, coverage
pypy inst: /home/jinghaos/projects/wltrace/.tox/dist/wltrace-1.0.3.zip

```
The `pypy create` and `pypy installdeps` steps were missing on Travis. Any hints will be appreciated.

**Comment by jhshi** [comment]
Never mind, I found the problem was my `setup.py`: the `sdist` step failed because `numpy` was not present, `tox` did not even get a chance to install the deps yet.

**Comment by ryanhiebert** [comment]
Nice. That makes sense, but I wouldn't have thought of it!
