### ISSUE TITLE
nightly is now Python 3.7 and fails

### ISSUE THREAD

**Issue by jayvdb** [ryanhiebert/tox-travis#31]
Using tox-travis with nightly now shows

```
$ pip install tox-travis
$ tox
ERROR: unknown environment 'py37'
```

**Comment by jayvdb** [comment]
fwiw, using `python: 3.6` breaks in travis.  I am pretty sure this has been raised in the public travis issues repo.

```
Using worker: worker-linux-docker-91207869.prod.travis-ci.org:travis-linux-3

...
3.6 is not installed; attempting download
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

The command "sudo tar xjf python-3.6.tar.bz2 --directory /" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by ryanhiebert** [comment]
I think the py37 thing is because that's not yet known to tox. That's a bug in tox, in my opinion, and I'm sure it'll be fixed in short order.

I'm not sure of the other is a bug, otay need to be declared as the beta version, since the stable version isn't out yet.

**Comment by jayvdb** [comment]
Correct on all counts ;-)

https://github.com/tox-dev/tox/pull/382
