### ISSUE TITLE
Using tox-travis hangs builds on PyPy3

### ISSUE THREAD

**Issue by ofek** [ryanhiebert/tox-travis#38]
I'm using tox-travis b/c of the included PyPy3 fix. For some reason unbeknownst to me, using tox-travis makes builds hang on PyPy3. This hanging always occurs after tests complete and before `coverage combine --append`. Repo: https://github.com/ofek/bit and example builds https://travis-ci.org/ofek/bit/builds/175390369 & https://travis-ci.org/ofek/bit/builds/175393268.

@jayvdb @ryanhiebert Am I doing something wrong?

edit: it sometimes hangs on other envs; py3.5 here [https://travis-ci.org/ofek/bit/builds/175395403](url)

edit: fixed broken links (@rpkilby)

**Comment by ofek** [comment]
I'm closing this. It appears to be that Travis doesn't play nicely with multiprocessing.

**Comment by rpkilby** [comment]
I don't fully understand the details, but this is something I've had trouble with in the past. Essentially, multiprocessing doesn't work when initialized under a daemonized subprocess. For example, had issues w/ multiprocessing and gunicorn as well as celery.
