### ISSUE TITLE
Don't attempt after on pull requests

### ISSUE THREAD

**Issue by ryanhiebert** [ryanhiebert/tox-travis#46]
Pull requests from another repository don't have the ability to read secure environment variables (rightly). There are two possible options:

1) Moving the secure environment variables to the web-based repository configuration may allow us to let the credentials go through to pull requests.
2) We could disable after for pull requests, or perhaps for pull requests _that aren't from this repository_.

Perhaps the right balance would be to check if it's a pull request, and if so, allow missing required environment variables for after waiting to just mean that after waiting is disabled.

Possibly related to #42. Problem showed up in #45.

**Comment by rpkilby** [comment]
Doing a little bit of work on this.

1. I don't think the web-based configuration allows for secure environment variables. If it does, my guess is that these environment variables would *also* not be visible to pull requests.
2. I don't use the after-all feature so my imagination is limited here, but is there a use case for allowing external pull requests to interact with the after-all feature? 
    - The only way to detect if a PR is from another repository is a combination of `TRAVIS_SECURE_ENV_VARS` and `TRAVIS_PULL_REQUEST`.

**Comment by ryanhiebert** [comment]
The only use-case I can see for it is for _us_. We want to be able to confirm that it's still working. In the general case, though, I expect that it's really not going to be helpful, so we can instead just have it do those checks on the master branch.

Perhaps the right thing to do is the same thing that Travis does for Pull Requests and the deploy section: they are ignored entirely. A pull request can never be deployed. That seems like a good thing to me. Deploying is _my_ only use-case for `after`, so it would be fine with me if it never worked with pull requests.

Even if I'm missing a case, as long as it's not obvious to anyone else here, I'd say it's probably fine to add that, since it's breaking our pull requests, and I'd expect it to break most other people's too.

**Comment by ryanhiebert** [comment]
You're correct that it wouldn't apply to forks, including pull requests, which would be the only right choice for secrets. It's actually great that I don't need to have the secure environment variable in the `travis.yml`, I think it belongs in a repository setting instead anyway.

https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by ryanhiebert** [comment]
Honestly, I'm debating the value of having after-all enabled _at all_ for pull requests, apart from the obvious case of our repository, since it would be testing the feature. Ultimately, I think we'll just have to test things as much as possible against Travis documented env vars interface, and not have it actually performing the after step for pull requests.

**Comment by rpkilby** [comment]
Have you had a chance to look at #50 yet?

**Comment by ryanhiebert** [comment]
Yep. Gonna comment on that in a sec.
