### ISSUE TITLE
Limit environments based on environment variable

### ISSUE THREAD

**Issue by Bouke** [ryanhiebert/tox-travis#47]
First off, great tool, scratches an itch I've been having. I have a question related to how to configure this to build the following. I want a different Travis job for each of the environments, to keep the history inside Travis easily browseable.

* [x] py{27,34,35}-{dj18,dj19,dj110} (see [here](https://travis-ci.org/Bouke/django-user-sessions/builds/189319558))
* [ ] flake8: this currently kicks off a build for all environments (see [here](https://travis-ci.org/Bouke/django-user-sessions/jobs/189319574)).

In my `tox.ini` I have the following; I would expect that setting `FLAKE8=YES` in the environment would restrict the envlist to only `flake8`;
```
[travis:env]
FLAKE8 =
    YES: flake8
```

Additionally I would like to enable code coverage for a selected few environments. So instead of `make test` it would need to be `make coverage`. This is probably a question for tox itself, but maybe there's a nice way to solve it integrally?

`travis.yml`
```
language: python
python:
 - 2.7
 - 3.4
 - 3.5
env:
 - DJANGO=1.8
 - DJANGO=1.9
 - DJANGO=1.10
matrix:
  include:
    - python: 3.5
      env: DJANGO=1.10 COVERAGE=YES
    - python: 3.5
      env: FLAKE8=YES
install: pip install tox-travis
script: tox
```

`tox.ini`
```[tox]
envlist =
    py{27,34,35}-{dj18,dj19,dj110},
    flake8

[travis]
python =
    2.7: py27
    3.4: py34
    3.5: py35

[travis:env]
DJANGO =
    1.8: dj18
    1.9: dj19
    1.10: dj110
FLAKE8 =
    YES: flake8

[testenv]
commands = make test
deps =
    dj18: Django>=1.8,<1.9
    dj19: Django>=1.9,<1.10
    dj110: Django>=1.10,<1.11
    flake8: flake8
whitelist_externals = make

[testenv:flake8]
commands = make flake8
```

**Comment by rpkilby** [comment]
Hi @Bouke Is there a reason you want to run coverage for a subset of envs but not all of them? My understanding is that people usually opt to run coverage for one specific env or for all envs (except for special envs like flake8). 

Either way, not entirely sure but I think this could be done purely in tox.

```ini
[testenv]
commands = make test
deps =
    ...

[testenv:py35-dj110]
commands = make coverage
```

The above would pull defaults from `[testenv]`, but then override the test commands for the one environment. 

Also, I think you can simplify the flake8 setup by using just `TOXENV`. You don't necessarily have to use `[travis:env]` handling for this. 

```yaml
matrix:
  include:
    - python: 3.5
      env: TOXENV=flake8
```

```ini
[testenv:flake8]
commands = make flake8
deps = 
    flake8
```

**Comment by ryanhiebert** [comment]
That's how I'd do it too. Manually overriding TOXENV is a really clean way to run exactly what you want, and Tox-Travis doesn't mess with this very nice feature of Tox, even though it uses it under the hood.

Here's the thing you're missing for your FLAKE8 env variable. There's an automatic `pyXX` factor added whenever `python: 3.5` is set, so if you wanted it to match that way, it would have to be called `py35-flake` or something like that, so that it would match the `py35` factor that would be implied by having `python: 3.5` in the travis config. You can't remove the `python: 3.5`, because that would likely do all kinds of screwy things.

I use codecov on all my environments, and it's very nice. It automatically keeps clean record of different runs on Travis AFA OS and Python version (python version had a bug that just got fixed, not sure if it's been released yet), and if you want it to tell you about other env vars, then you can tell it to look for those too.

You can see how I use it on https://github.com/pylti/lti. Look at both the `.travis.yml` and the `tox.ini` to see how I'm using it.

I hope that helps!

**Comment by Bouke** [comment]
Great feedback, thank you both! Using TOXENV this way is very nice, allows for fine-grained control over additional environments to run. It might be helpful to include a note about this in the documentation, to point people to this feature.

My thinking of not testing with coverage for all environments was that I didn't want to take too many resources from the community provided Travis build machines. However after some experimenting it seems that the difference is neglectable.

Also interesting idea you have in `lti`, to automate pushing new versions to pypi. There's also (travis-bump-version)[0] that will use `bumpversion` to a new version, to completely automate this.

[0]: https://github.com/polysquare/travis-bump-version

**Comment by ryanhiebert** [comment]
I agree about putting it in the docs.i have some docs in progress, but it's still early days.

I've heard of bumpversion, but haven't tried it out quite yet.

**Comment by Bouke** [comment]
I'm still not sure how to make this work. I have the following envlist:

```ini
envlist =
    py{27,34,35}-dj18{,-yubikey,-custom_user},
```

Now I want to only build `py27-dj18-custom_user`. So I define my build matrix in Travis:

```yaml
python:
 - 2.7
 - 3.4
 - 3.5

env:
 - DJANGO=1.8
 - DJANGO=1.8 CUSTOM_USER=1
 - DJANGO=1.8 YUBIKEY=1
```

and add the following to ``tox.ini``:

```ini
[travis]
python =
    2.7: py27
    3.4: py34
    3.5: py35
    3.6: py36
unignore_outcomes = True

[travis:env]
DJANGO =
    1.8: dj18
CUSTOM_USER =
    1: custom_user
YUBIKEY =
    1: yubikey
```

However, this doesn't work;

```
TRAVIS_PYTHON_VERSION=2.7 TRAVIS=1 DJANGO=1.8 tox
  py27-dj18: commands succeeded
  py27-dj18-yubikey: commands succeeded
  py27-dj18-custom_user: commands succeeded
  congratulations :)

TRAVIS_PYTHON_VERSION=2.7 TRAVIS=1 DJANGO=1.8 YUBIKEY=1 tox
  py27-dj18-yubikey: commands succeeded
  congratulations :)
 
TRAVIS_PYTHON_VERSION=2.7 TRAVIS=1 DJANGO=1.8 CUSTOM_USER=1 tox
  py27-dj18-custom_user: commands succeeded
  congratulations :)
```

In the first call, I would only like to build `py27-dj18`, not the other ones as well. How can I achieve this without duplicating my build matrix inside `.travis.yml`?

**Comment by ryanhiebert** [comment]
I'm about to step out for a bit, but I will respond to this later.

**Comment by ryanhiebert** [comment]
Here's what I would do:

`tox.ini`:

```ini
[tox]
envlist = py{27,34,35}-dj18-{normal,yubikey,custom_user}

[travis]
unignore_outcomes = True  # You're using master, right?
# The python key isn't needed, because what you've set is default

[travis:env]
DJANGO =
  1.8: dj18
VARIANT =
  normal: normal
  yubikey: yubikey
  custom_user: custom_user
```

and `.travis.yml`:

```yaml
python:
 - 2.7
 - 3.4
 - 3.5

env:
 - DJANGO=1.8 VARIANT=normal
 - DJANGO=1.8 VARIANT=yubikey
 - DJANGO=1.8 VARIANT=custom_user
```

**Comment by Bouke** [comment]
Ah yes, that's a nice alternative, thanks!
