### ISSUE TITLE
Autogenerate .travis.yml

### ISSUE THREAD

**Issue by ryanhiebert** [ryanhiebert/tox-travis#5]
Since we've got information on how Travis CI and Tox should talk to each other, we may be able to help implement a rudimentary `.travis.yml` file, ready for further customization. It can't be a complete solution, but it can be an easy way to start.

If possible, it would be nice for it to be some kind of a sub-command of `tox`, for instance, `tox --travis-gen` or something similar, to avoid another top-level command.

This idea originated with a comment by @henriquebastos on #4.

**Comment by luzfcb** [comment]
a time ago I saw this https://github.com/msabramo/python-panci , but do not know if it works correctly

**Comment by henriquebastos** [comment]
Fábio, I tried, but I didn't had luck with it. When I tried tox-travis it
was magic! :)

**Comment by ryanhiebert** [comment]
Honestly, I don't see enough benefit from this. It would only be possibly useful for one go, and then it's likely to be missing edge-cases and other Travis configuration. I think it's best to just let users understand what they're doing.
