### ISSUE TITLE
"Advanced configuration" not working as documented

### ISSUE THREAD

**Issue by posita** [ryanhiebert/tox-travis#64]
After reading [this](https://tox-travis.readthedocs.io/en/stable/toxenv.html#advanced-configuration), I created [this `.travis.yml`](https://github.com/posita/txrc/blob/802536857d8400db8cf4f340cf73797d39355544/.travis.yml) and [this `tox.ini`](https://github.com/posita/txrc/blob/802536857d8400db8cf4f340cf73797d39355544/tox.ini). However, my `lint`, and `check` targets are not being called as expected. I expected that (e.g):

- Python `"2.7"` and `TWISTED="17.1"` would call `py27-twisted_17_1` and `lint`, but [it only calls `py27-twisted_17_1`](https://travis-ci.org/posita/txrc/jobs/210718296#L238).
- Python `"3.5"` and `TWISTED="17.1"` would call `py35-twisted_17_1`, `lint`, and `check`, but [it only calls `py35-twisted_17_1`](https://travis-ci.org/posita/txrc/jobs/210718314#L226).

**Comment by posita** [comment]
Oops! I think I see the problem. It's `[travis:env]`, _not_ `[tox:travis:env]`. 😳 My apologies for the erroneous issue. 😞 Closing as `invalid`.

**Comment by posita** [comment]
Editing original comment and reopening.

**Comment by ryanhiebert** [comment]
You've added `lint` to the Python factors. That's good. But because you're also using the `env` factor, and it matches, you've got to also add `lint` to those factors too. When looking at a single factor (e.g. an env factor like `MYFACTOR = spam: one_part, two_part`), only one of the comma separated list of parts needs to match. But across various factors (env, python, etc) they _must_ match, or else it'll be rejected.

**Comment by posita** [comment]
I'm not sure I understand thoroughly, but my original issue may be `invalid`.

**_TL;DR_** - Given this `.travis.yml`…

``` yml
python:
    - "2.7"
    - "3.5"

env:
    - TWISTED="17.1"
    - TWISTED="trunk"
```

…this `tox.ini` will work as I expected…

``` ini
envlist = py{27,35}-twisted_{17_1,trunk}, lint, check

[travis]
python =
    2.7: py27, lint
    3.5: py35, lint, check

[travis:env]
TWISTED =
    17.1: twisted_17_1, lint, check
    trunk: twisted_trunk
```

…but this `tox.ini` will not…

``` ini
# …
[travis]
2.7 = py27, lint
3.5 = py35, lint, check
# …
```

See https://gitter.im/ryanhiebert/tox-travis?at=58c8194b00c00c3d4f07d2b5 _et seq._ For additional discussion.

Perhaps it makes sense to add a counter example to [the advanced configuration docs](https://tox-travis.readthedocs.io/en/stable/toxenv.html#advanced-configuration) explaining the difference between (e.g.) my non-working approach and my working approach?

**Comment by ryanhiebert** [comment]
I believe that you've correctly identified this as invalid.

I do think improving the docs would be great, I'm just not quite sure how. Writing docs can be difficult, especially when you're dealing with imprecise or overloaded terminology. Our discussion on Gitter about the terminology is one prime example of how terminology is confusing our documentation.

I think a great improvement in the docs would be to add a glossary of terms that we use to describe the Travis and Tox configurations, come up with a better word for our configuration items (which I've badly called factors and caused clashing with Tox factors), and then adjust all the docs to make sure the terms are used consistently.

Anyway, I'll gladly work with anyone willing to put some time into improving the docs. I'm sure I'll get to it, but I can't attach any specific timeframe to it.
