### ISSUE TITLE
Python-nightly tox started to fail

### ISSUE THREAD

**Issue by mcyprian** [ryanhiebert/tox-travis#68]
I am not sure if this is the correct project to report this. Invocation of tox in [python-nightly job](https://travis-ci.org/fedora-python/pyp2rpm/jobs/220581520) of pyp2rpm's builds in travis started to fail.

.travis.yml file content: https://github.com/fedora-python/pyp2rpm/blob/master/.travis.yml

**Comment by rpkilby** [comment]
Off the cuff, this looks like some sort of problem w/ python 3.7?

```
/opt/python/3.7-dev/lib/python3.7/distutils/dist.py:261: 
UserWarning: Unknown distribution option: 'use_scm_version'
```

**Comment by ryanhiebert** [comment]
I agree with that assessment. I'm not sure what's calling distutils. It's not Tox-Travis, at least directly.

**Comment by ryanhiebert** [comment]
I see that you don't have a `py37` env in your `tox.ini`. You might consider adding nightly to the Travis allowed failures until you figure out the problem, unless you think that supporting 3.7 is critical to your project. This would keep the tests running, but not make them noisy and cause the build to fail.

**Comment by mcyprian** [comment]
Maybe some of the dependencies cannot by installed from setup.py using py37. I will definitely add it to allowed failures, thanks for your advice.

**Comment by ryanhiebert** [comment]
Sounds good. If you find that this does seem to be a bug in Tox-Travis, feel free to re-open or continue conversation on this issue.
